/**
 * Mock Data Service for Local Development
 *
 * Provides realistic demo data for the AngebotsAgent app
 * when running without Supabase connection.
 *
 * Based on real offer analysis from German construction trades.
 */

import type {
  Company,
  Project,
  Document,
  ExtractedData,
  TakeoffResult,
  PriceLibraryItem,
  OfferDraft,
  OfferLineItem,
  RiskFlag,
} from '@/types/database';

// =============================================================================
// DEMO USER & COMPANY
// =============================================================================

export const DEMO_USER = {
  id: 'demo-user-001',
  email: 'demo@mustermann-trockenbau.de',
  created_at: '2024-01-15T10:00:00Z',
  user_metadata: {
    full_name: 'Klaus Mustermann',
  },
};

export const DEMO_COMPANY: Company = {
  id: 'demo-company-001',
  name: 'Mustermann Trockenbau GmbH',
  trade: 'trockenbau',
  street: 'Handwerkerstraße 15',
  zip_code: '60311',
  city: 'Frankfurt am Main',
  country: 'Deutschland',
  phone: '+49 69 123456',
  email: 'info@mustermann-trockenbau.de',
  website: 'www.mustermann-trockenbau.de',
  tax_id: '012/345/67890',
  vat_id: 'DE123456789',
  commercial_register: 'HRB 12345, AG Frankfurt',
  default_markup_percent: 15,
  default_risk_percent: 5,
  default_overhead_percent: 10,
  logo_path: null,
  offer_template: {},
  invoice_template: {},
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
  created_by: DEMO_USER.id,
};

// =============================================================================
// DEMO PROJECTS
// =============================================================================

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'project-001',
    company_id: DEMO_COMPANY.id,
    title: 'Bürogebäude LEIQ Offenbach',
    project_number: '2024-001',
    description: 'Neubau Bürogebäude mit 5 Geschossen, ca. 3.500 m² Trockenbaufläche',
    client_name: 'LEIQ Projektentwicklung GmbH',
    client_contact: 'Herr Schmidt',
    client_email: 'schmidt@leiq-projekt.de',
    client_phone: '+49 69 987654',
    client_address: 'Kaiserstraße 50, 60329 Frankfurt',
    site_street: 'Kaiserleistraße 29',
    site_zip_code: '63067',
    site_city: 'Offenbach am Main',
    site_country: 'Deutschland',
    submission_deadline: '2024-02-15',
    start_date: '2024-04-01',
    end_date: '2024-10-31',
    status: 'draft',
    total_net: 245000,
    total_gross: 291550,
    tags: ['Neubau', 'Büro', 'Großprojekt'],
    notes: 'Anfrage über GU Hochtief erhalten',
    created_at: '2024-01-20T09:00:00Z',
    updated_at: '2024-01-25T14:30:00Z',
    created_by: DEMO_USER.id,
  },
  {
    id: 'project-002',
    company_id: DEMO_COMPANY.id,
    title: 'Wohnanlage Am Stadtpark',
    project_number: '2024-002',
    description: 'Mehrfamilienhaus mit 24 Wohneinheiten, Trockenbau Innenausbau',
    client_name: 'Stadtpark Wohnbau GmbH',
    client_contact: 'Frau Müller',
    client_email: 'mueller@stadtpark-wohnbau.de',
    client_phone: '+49 69 456789',
    client_address: 'Parkstraße 10, 60322 Frankfurt',
    site_street: 'Am Stadtpark 5-7',
    site_zip_code: '60322',
    site_city: 'Frankfurt am Main',
    site_country: 'Deutschland',
    submission_deadline: '2024-02-28',
    start_date: '2024-05-15',
    end_date: '2024-12-15',
    status: 'in_review',
    total_net: 178500,
    total_gross: 212415,
    tags: ['Wohnbau', 'Mehrfamilienhaus'],
    notes: null,
    created_at: '2024-01-22T11:00:00Z',
    updated_at: '2024-01-26T10:00:00Z',
    created_by: DEMO_USER.id,
  },
  {
    id: 'project-003',
    company_id: DEMO_COMPANY.id,
    title: 'Umbau Ladenlokal Zeil',
    project_number: '2024-003',
    description: 'Umbau Einzelhandelsfläche, neue Zwischenwände und Abhangdecken',
    client_name: 'Retail Spaces Frankfurt GmbH',
    client_contact: 'Herr Weber',
    client_email: 'weber@retail-spaces.de',
    client_phone: '+49 69 111222',
    client_address: 'Zeil 100, 60313 Frankfurt',
    site_street: 'Zeil 85',
    site_zip_code: '60313',
    site_city: 'Frankfurt am Main',
    site_country: 'Deutschland',
    submission_deadline: '2024-01-30',
    start_date: '2024-02-15',
    end_date: '2024-03-31',
    status: 'submitted',
    total_net: 45200,
    total_gross: 53788,
    tags: ['Umbau', 'Einzelhandel', 'Eilauftrag'],
    notes: 'Kurze Bauzeit - Nachtarbeit möglich',
    created_at: '2024-01-10T08:00:00Z',
    updated_at: '2024-01-28T16:00:00Z',
    created_by: DEMO_USER.id,
  },
];

// =============================================================================
// DEMO DOCUMENTS
// =============================================================================

export const DEMO_DOCUMENTS: Document[] = [
  {
    id: 'doc-001',
    project_id: 'project-001',
    name: 'Leistungsverzeichnis Trockenbau',
    original_filename: 'LV_Trockenbau_LEIQ_2024.pdf',
    storage_path: '/demo/documents/lv-trockenbau.pdf',
    file_size: 2450000,
    mime_type: 'application/pdf',
    document_type: 'leistungsverzeichnis',
    status: 'extracted',
    page_count: 45,
    processing_started_at: '2024-01-20T09:15:00Z',
    processing_completed_at: '2024-01-20T09:18:00Z',
    processing_error: null,
    scale: null,
    drawing_number: null,
    revision: 'Rev. A',
    extraction_summary: { positions: 87, total_quantity: 3520 },
    created_at: '2024-01-20T09:10:00Z',
    updated_at: '2024-01-20T09:18:00Z',
    uploaded_by: DEMO_USER.id,
  },
  {
    id: 'doc-002',
    project_id: 'project-001',
    name: 'Grundriss EG',
    original_filename: 'GR_EG_LEIQ_A101.pdf',
    storage_path: '/demo/documents/gr-eg.pdf',
    file_size: 5800000,
    mime_type: 'application/pdf',
    document_type: 'grundriss',
    status: 'reviewed',
    page_count: 1,
    processing_started_at: '2024-01-20T09:20:00Z',
    processing_completed_at: '2024-01-20T09:22:00Z',
    processing_error: null,
    scale: '1:100',
    drawing_number: 'A101',
    revision: 'Rev. B',
    extraction_summary: { rooms: 24, total_area: 850 },
    created_at: '2024-01-20T09:19:00Z',
    updated_at: '2024-01-21T10:00:00Z',
    uploaded_by: DEMO_USER.id,
  },
  {
    id: 'doc-003',
    project_id: 'project-001',
    name: 'Grundriss 1.OG',
    original_filename: 'GR_1OG_LEIQ_A102.pdf',
    storage_path: '/demo/documents/gr-1og.pdf',
    file_size: 5600000,
    mime_type: 'application/pdf',
    document_type: 'grundriss',
    status: 'extracted',
    page_count: 1,
    processing_started_at: '2024-01-20T09:25:00Z',
    processing_completed_at: '2024-01-20T09:27:00Z',
    processing_error: null,
    scale: '1:100',
    drawing_number: 'A102',
    revision: 'Rev. B',
    extraction_summary: { rooms: 22, total_area: 780 },
    created_at: '2024-01-20T09:24:00Z',
    updated_at: '2024-01-20T09:27:00Z',
    uploaded_by: DEMO_USER.id,
  },
  {
    id: 'doc-004',
    project_id: 'project-001',
    name: 'Baubeschreibung',
    original_filename: 'Baubeschreibung_LEIQ_2024.pdf',
    storage_path: '/demo/documents/baubeschreibung.pdf',
    file_size: 890000,
    mime_type: 'application/pdf',
    document_type: 'baubeschreibung',
    status: 'uploaded',
    page_count: 12,
    processing_started_at: null,
    processing_completed_at: null,
    processing_error: null,
    scale: null,
    drawing_number: null,
    revision: null,
    extraction_summary: {},
    created_at: '2024-01-20T09:30:00Z',
    updated_at: '2024-01-20T09:30:00Z',
    uploaded_by: DEMO_USER.id,
  },
];

// =============================================================================
// DEMO EXTRACTED DATA (LV Positions)
// =============================================================================

export const DEMO_EXTRACTED_DATA: ExtractedData[] = [
  {
    id: 'ext-001',
    document_id: 'doc-001',
    project_id: 'project-001',
    position_number: '01.01.01.0010',
    oz_number: '0010',
    title: 'GK-Ständerwand W111, einfach beplankt',
    description: 'Gipskarton-Ständerwand nach DIN 4103 Teil 1, Wandtyp Knauf W111, Ständerwerk CW 75/06, einseitig beplankt mit GKB 12,5 mm, Oberfläche Q2',
    long_text: 'Gipskarton-Ständerwand als Raumtrennwand nach DIN 4103 Teil 1...',
    quantity: 125.5,
    unit: 'm2',
    page_number: 8,
    page_reference: 'Seite 8, Position 01.01.01.0010',
    bounding_box: null,
    extraction_confidence: 0.95,
    is_verified: true,
    verified_by: DEMO_USER.id,
    verified_at: '2024-01-21T10:00:00Z',
    raw_extraction: {},
    created_at: '2024-01-20T09:18:00Z',
    updated_at: '2024-01-21T10:00:00Z',
  },
  {
    id: 'ext-002',
    document_id: 'doc-001',
    project_id: 'project-001',
    position_number: '01.01.01.0020',
    oz_number: '0020',
    title: 'GK-Ständerwand W112, doppelt beplankt',
    description: 'Gipskarton-Ständerwand nach DIN 4103 Teil 1, Wandtyp Knauf W112, Ständerwerk CW 75/06, beidseitig doppelt beplankt mit GKB 12,5 mm, Oberfläche Q3',
    long_text: 'Gipskarton-Ständerwand als Raumtrennwand nach DIN 4103 Teil 1...',
    quantity: 350.0,
    unit: 'm2',
    page_number: 9,
    page_reference: 'Seite 9, Position 01.01.01.0020',
    bounding_box: null,
    extraction_confidence: 0.92,
    is_verified: true,
    verified_by: DEMO_USER.id,
    verified_at: '2024-01-21T10:05:00Z',
    raw_extraction: {},
    created_at: '2024-01-20T09:18:00Z',
    updated_at: '2024-01-21T10:05:00Z',
  },
  {
    id: 'ext-003',
    document_id: 'doc-001',
    project_id: 'project-001',
    position_number: '01.01.02.0010',
    oz_number: '0010',
    title: 'GK-Ständerwand W115, Brandschutz F90',
    description: 'Gipskarton-Ständerwand Brandwand F90-A nach DIN 4102, Wandtyp Knauf W115, Ständerwerk CW 100/06, beidseitig doppelt beplankt mit GKF 15 mm',
    long_text: 'Brandschutzwand F90-A als Treppenhaus-Abschluss...',
    quantity: 85.0,
    unit: 'm2',
    page_number: 10,
    page_reference: 'Seite 10, Position 01.01.02.0010',
    bounding_box: null,
    extraction_confidence: 0.88,
    is_verified: false,
    verified_by: null,
    verified_at: null,
    raw_extraction: {},
    created_at: '2024-01-20T09:18:00Z',
    updated_at: '2024-01-20T09:18:00Z',
  },
  {
    id: 'ext-004',
    document_id: 'doc-001',
    project_id: 'project-001',
    position_number: '01.02.01.0010',
    oz_number: '0010',
    title: 'GK-Abhangdecke D112, geschlossene Fläche',
    description: 'Gipskarton-Abhangdecke nach DIN 18168, Deckentyp Knauf D112, Grundlattung CD 60/27, beplankt mit GKB 12,5 mm, Oberfläche Q2',
    long_text: 'Abhangdecke in Büroräumen, Abhängehöhe 30-50 cm...',
    quantity: 620.0,
    unit: 'm2',
    page_number: 15,
    page_reference: 'Seite 15, Position 01.02.01.0010',
    bounding_box: null,
    extraction_confidence: 0.94,
    is_verified: true,
    verified_by: DEMO_USER.id,
    verified_at: '2024-01-21T10:10:00Z',
    raw_extraction: {},
    created_at: '2024-01-20T09:18:00Z',
    updated_at: '2024-01-21T10:10:00Z',
  },
  {
    id: 'ext-005',
    document_id: 'doc-001',
    project_id: 'project-001',
    position_number: '01.02.02.0010',
    oz_number: '0010',
    title: 'GK-Abhangdecke D113, Nassraum',
    description: 'Gipskarton-Abhangdecke für Nassräume nach DIN 18168, Deckentyp Knauf D113, imprägnierte Platten GKBI 12,5 mm',
    long_text: 'Abhangdecke in WC-Anlagen und Teeküchen...',
    quantity: 45.0,
    unit: 'm2',
    page_number: 16,
    page_reference: 'Seite 16, Position 01.02.02.0010',
    bounding_box: null,
    extraction_confidence: 0.91,
    is_verified: false,
    verified_by: null,
    verified_at: null,
    raw_extraction: {},
    created_at: '2024-01-20T09:18:00Z',
    updated_at: '2024-01-20T09:18:00Z',
  },
];

// =============================================================================
// DEMO PRICE LIBRARY (Trockenbau)
// =============================================================================

export const DEMO_PRICE_LIBRARY: PriceLibraryItem[] = [
  // Wände
  {
    id: 'price-001',
    company_id: DEMO_COMPANY.id,
    item_code: 'TB-W111',
    name: 'GK-Ständerwand W111',
    description: 'Einfach beplankt, CW 75/06, GKB 12,5mm, Q2',
    category: 'Wände',
    subcategory: 'Ständerwände',
    trade: 'trockenbau',
    unit: 'm2',
    unit_price: 28.50,
    material_cost: 12.50,
    labor_cost: 14.00,
    equipment_cost: 2.00,
    other_cost: null,
    labor_hours: 0.35,
    valid_from: '2024-01-01',
    valid_until: '2024-12-31',
    source: 'Kalkulation 2024',
    notes: 'Standardausführung',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    created_by: DEMO_USER.id,
  },
  {
    id: 'price-002',
    company_id: DEMO_COMPANY.id,
    item_code: 'TB-W112',
    name: 'GK-Ständerwand W112',
    description: 'Doppelt beplankt, CW 75/06, GKB 12,5mm, Q3',
    category: 'Wände',
    subcategory: 'Ständerwände',
    trade: 'trockenbau',
    unit: 'm2',
    unit_price: 45.00,
    material_cost: 22.00,
    labor_cost: 20.00,
    equipment_cost: 3.00,
    other_cost: null,
    labor_hours: 0.50,
    valid_from: '2024-01-01',
    valid_until: '2024-12-31',
    source: 'Kalkulation 2024',
    notes: 'Inkl. Verspachtelung Q3',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    created_by: DEMO_USER.id,
  },
  {
    id: 'price-003',
    company_id: DEMO_COMPANY.id,
    item_code: 'TB-W115',
    name: 'GK-Brandwand W115 F90',
    description: 'Brandwand F90-A, CW 100/06, GKF 15mm doppelt',
    category: 'Wände',
    subcategory: 'Brandschutzwände',
    trade: 'trockenbau',
    unit: 'm2',
    unit_price: 85.00,
    material_cost: 45.00,
    labor_cost: 35.00,
    equipment_cost: 5.00,
    other_cost: null,
    labor_hours: 0.85,
    valid_from: '2024-01-01',
    valid_until: '2024-12-31',
    source: 'Kalkulation 2024',
    notes: 'Inkl. Mineralwolle 60mm',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    created_by: DEMO_USER.id,
  },
  // Decken
  {
    id: 'price-004',
    company_id: DEMO_COMPANY.id,
    item_code: 'TB-D112',
    name: 'GK-Abhangdecke D112',
    description: 'Geschlossene Fläche, CD 60/27, GKB 12,5mm, Q2',
    category: 'Decken',
    subcategory: 'Abhangdecken',
    trade: 'trockenbau',
    unit: 'm2',
    unit_price: 38.00,
    material_cost: 16.00,
    labor_cost: 19.00,
    equipment_cost: 3.00,
    other_cost: null,
    labor_hours: 0.45,
    valid_from: '2024-01-01',
    valid_until: '2024-12-31',
    source: 'Kalkulation 2024',
    notes: 'Abhängehöhe bis 50cm',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    created_by: DEMO_USER.id,
  },
  {
    id: 'price-005',
    company_id: DEMO_COMPANY.id,
    item_code: 'TB-D113',
    name: 'GK-Abhangdecke D113 Nassraum',
    description: 'Nassraumdecke, CD 60/27, GKBI 12,5mm',
    category: 'Decken',
    subcategory: 'Abhangdecken',
    trade: 'trockenbau',
    unit: 'm2',
    unit_price: 48.00,
    material_cost: 22.00,
    labor_cost: 22.00,
    equipment_cost: 4.00,
    other_cost: null,
    labor_hours: 0.55,
    valid_from: '2024-01-01',
    valid_until: '2024-12-31',
    source: 'Kalkulation 2024',
    notes: 'Imprägnierte Platten',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    created_by: DEMO_USER.id,
  },
  // Vorsatzschalen
  {
    id: 'price-006',
    company_id: DEMO_COMPANY.id,
    item_code: 'TB-W625',
    name: 'Vorsatzschale W625',
    description: 'Freistehend, CW 50/06, GKB 12,5mm einfach',
    category: 'Wände',
    subcategory: 'Vorsatzschalen',
    trade: 'trockenbau',
    unit: 'm2',
    unit_price: 32.00,
    material_cost: 14.00,
    labor_cost: 15.00,
    equipment_cost: 3.00,
    other_cost: null,
    labor_hours: 0.38,
    valid_from: '2024-01-01',
    valid_until: '2024-12-31',
    source: 'Kalkulation 2024',
    notes: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    created_by: DEMO_USER.id,
  },
  // Zusatzleistungen
  {
    id: 'price-007',
    company_id: DEMO_COMPANY.id,
    item_code: 'TB-ZL01',
    name: 'Türausschnitt einf. Tür',
    description: 'Ausschnitt für Standardtür bis 1,01 x 2,135m',
    category: 'Zusatzleistungen',
    subcategory: 'Ausschnitte',
    trade: 'trockenbau',
    unit: 'stk',
    unit_price: 65.00,
    material_cost: 15.00,
    labor_cost: 45.00,
    equipment_cost: 5.00,
    other_cost: null,
    labor_hours: 1.10,
    valid_from: '2024-01-01',
    valid_until: '2024-12-31',
    source: 'Kalkulation 2024',
    notes: 'Inkl. UA-Profil Verstärkung',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    created_by: DEMO_USER.id,
  },
  {
    id: 'price-008',
    company_id: DEMO_COMPANY.id,
    item_code: 'TB-ZL02',
    name: 'Eckschutzschiene',
    description: 'Alu-Eckschutzschiene montiert',
    category: 'Zusatzleistungen',
    subcategory: 'Zubehör',
    trade: 'trockenbau',
    unit: 'm',
    unit_price: 8.50,
    material_cost: 3.50,
    labor_cost: 4.50,
    equipment_cost: 0.50,
    other_cost: null,
    labor_hours: 0.12,
    valid_from: '2024-01-01',
    valid_until: '2024-12-31',
    source: 'Kalkulation 2024',
    notes: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    created_by: DEMO_USER.id,
  },
];

// =============================================================================
// DEMO TAKEOFF RESULTS
// =============================================================================

export const DEMO_TAKEOFF_RESULTS: TakeoffResult[] = [
  {
    id: 'takeoff-001',
    project_id: 'project-001',
    document_id: 'doc-002',
    extracted_data_id: 'ext-001',
    position_number: '01.01.01.0010',
    description: 'GK-Ständerwand W111, EG Flur',
    quantity: 48.5,
    unit: 'm2',
    source: 'measured',
    measurement_data: { width: 12.5, height: 3.88, deductions: [] },
    plan_page: 1,
    plan_zone: 'EG-Flur',
    is_verified: true,
    verified_by: DEMO_USER.id,
    verified_at: '2024-01-21T11:00:00Z',
    notes: 'Länge: 12,5m × Höhe: 3,88m',
    created_at: '2024-01-21T10:30:00Z',
    updated_at: '2024-01-21T11:00:00Z',
    created_by: DEMO_USER.id,
  },
  {
    id: 'takeoff-002',
    project_id: 'project-001',
    document_id: 'doc-002',
    extracted_data_id: 'ext-001',
    position_number: '01.01.01.0010',
    description: 'GK-Ständerwand W111, EG Büro 1.01-1.05',
    quantity: 85.0,
    unit: 'm2',
    source: 'measured',
    measurement_data: { rooms: ['1.01', '1.02', '1.03', '1.04', '1.05'] },
    plan_page: 1,
    plan_zone: 'EG-Büros',
    is_verified: true,
    verified_by: DEMO_USER.id,
    verified_at: '2024-01-21T11:15:00Z',
    notes: 'Trennwände Büros EG',
    created_at: '2024-01-21T10:45:00Z',
    updated_at: '2024-01-21T11:15:00Z',
    created_by: DEMO_USER.id,
  },
];

// =============================================================================
// DEMO RISK FLAGS
// =============================================================================

export const DEMO_RISK_FLAGS: RiskFlag[] = [
  {
    id: 'risk-001',
    project_id: 'project-001',
    document_id: 'doc-001',
    extracted_data_id: 'ext-001',
    offer_line_item_id: null,
    takeoff_result_id: 'takeoff-001',
    title: 'Mengenabweichung GK-Wand W111',
    description: 'LV gibt 125,5 m² an, Planmessung ergibt 148,0 m² (Abweichung +18%)',
    category: 'mengenabweichung',
    severity: 'high',
    source_reference: 'LV Seite 8, Position 01.01.01.0010',
    page_reference: 'Plan A101, EG',
    estimated_impact_min: 640,
    estimated_impact_max: 850,
    detection_method: 'quantity_comparison',
    confidence: 0.92,
    ai_reasoning: 'Flächenberechnung aus Grundriss EG zeigt deutlich höhere Wandflächen als im LV angegeben.',
    is_resolved: false,
    resolution_notes: null,
    resolved_by: null,
    resolved_at: null,
    is_acknowledged: true,
    acknowledged_by: DEMO_USER.id,
    acknowledged_at: '2024-01-22T09:00:00Z',
    created_at: '2024-01-21T12:00:00Z',
    updated_at: '2024-01-22T09:00:00Z',
    created_by: null,
  },
  {
    id: 'risk-002',
    project_id: 'project-001',
    document_id: 'doc-001',
    extracted_data_id: 'ext-003',
    offer_line_item_id: null,
    takeoff_result_id: null,
    title: 'Brandschutzanforderung unklar',
    description: 'Position 01.01.02.0010 spezifiziert F90-A, aber Detailplanung zeigt F90-AB Anforderung für Treppenhaus',
    category: 'normabweichung',
    severity: 'critical',
    source_reference: 'LV Seite 10 vs. Brandschutzkonzept',
    page_reference: null,
    estimated_impact_min: 1200,
    estimated_impact_max: 2500,
    detection_method: 'specification_check',
    confidence: 0.78,
    ai_reasoning: 'Diskrepanz zwischen LV-Anforderung und Brandschutznachweis erkannt.',
    is_resolved: false,
    resolution_notes: null,
    resolved_by: null,
    resolved_at: null,
    is_acknowledged: false,
    acknowledged_by: null,
    acknowledged_at: null,
    created_at: '2024-01-21T12:15:00Z',
    updated_at: '2024-01-21T12:15:00Z',
    created_by: null,
  },
  {
    id: 'risk-003',
    project_id: 'project-001',
    document_id: 'doc-001',
    extracted_data_id: null,
    offer_line_item_id: null,
    takeoff_result_id: null,
    title: 'Fehlende Position: Revisionsklappe',
    description: 'In Abhangdecke D112 keine Revisionsklappen im LV enthalten, typischerweise 1 Stk. pro 25 m²',
    category: 'fehlende_position',
    severity: 'medium',
    source_reference: 'LV Seite 15-16',
    page_reference: null,
    estimated_impact_min: 450,
    estimated_impact_max: 750,
    detection_method: 'completeness_check',
    confidence: 0.85,
    ai_reasoning: 'Standard-Ausstattung für Bürogebäude-Abhangdecken fehlt im LV.',
    is_resolved: false,
    resolution_notes: null,
    resolved_by: null,
    resolved_at: null,
    is_acknowledged: false,
    acknowledged_by: null,
    acknowledged_at: null,
    created_at: '2024-01-21T12:30:00Z',
    updated_at: '2024-01-21T12:30:00Z',
    created_by: null,
  },
];

// =============================================================================
// DEMO OFFER DRAFT
// =============================================================================

export const DEMO_OFFER_DRAFTS: OfferDraft[] = [
  {
    id: 'offer-001',
    project_id: 'project-001',
    version: 1,
    is_current: true,
    parent_version_id: null,
    title: 'Angebot Trockenbauarbeiten LEIQ',
    offer_number: 'ANG-2024-001-A',
    offer_date: '2024-01-25',
    validity_days: 30,
    markup_percent: 15,
    risk_percent: 5,
    overhead_percent: 10,
    discount_percent: 0,
    subtotal_net: 195000,
    markup_amount: 29250,
    risk_amount: 9750,
    overhead_amount: 19500,
    discount_amount: 0,
    total_net: 245000,
    vat_percent: 19,
    vat_amount: 46550,
    total_gross: 291550,
    cover_text: 'Sehr geehrte Damen und Herren,\n\nfür die Trockenbauarbeiten am oben genannten Bauvorhaben bieten wir Ihnen nachfolgend unsere Leistungen an.',
    terms_and_conditions: 'Es gelten unsere Allgemeinen Geschäftsbedingungen sowie die VOB/B in der aktuellen Fassung.',
    notes: 'Erste Version, noch nicht final geprüft',
    status: 'draft',
    submitted_at: null,
    created_at: '2024-01-25T14:00:00Z',
    updated_at: '2024-01-25T14:30:00Z',
    created_by: DEMO_USER.id,
  },
];

// =============================================================================
// DEMO OFFER LINE ITEMS
// =============================================================================

export const DEMO_OFFER_LINE_ITEMS: OfferLineItem[] = [
  {
    id: 'item-001',
    offer_draft_id: 'offer-001',
    position_number: '01.01.01.0010',
    sort_order: 1,
    title: 'GK-Ständerwand W111, einfach beplankt',
    description: 'Gipskarton-Ständerwand nach DIN 4103 Teil 1, Wandtyp Knauf W111',
    long_text: null,
    quantity: 148.0,
    unit: 'm2',
    unit_price: 28.50,
    total_price: 4218.00,
    takeoff_result_id: 'takeoff-001',
    price_library_id: 'price-001',
    extracted_data_id: 'ext-001',
    item_markup_percent: null,
    item_discount_percent: null,
    is_optional: false,
    is_alternative: false,
    parent_item_id: null,
    internal_notes: 'Menge aus Planauswertung übernommen (LV: 125,5 m²)',
    created_at: '2024-01-25T14:10:00Z',
    updated_at: '2024-01-25T14:10:00Z',
  },
  {
    id: 'item-002',
    offer_draft_id: 'offer-001',
    position_number: '01.01.01.0020',
    sort_order: 2,
    title: 'GK-Ständerwand W112, doppelt beplankt',
    description: 'Gipskarton-Ständerwand nach DIN 4103 Teil 1, Wandtyp Knauf W112, Q3',
    long_text: null,
    quantity: 350.0,
    unit: 'm2',
    unit_price: 45.00,
    total_price: 15750.00,
    takeoff_result_id: null,
    price_library_id: 'price-002',
    extracted_data_id: 'ext-002',
    item_markup_percent: null,
    item_discount_percent: null,
    is_optional: false,
    is_alternative: false,
    parent_item_id: null,
    internal_notes: null,
    created_at: '2024-01-25T14:12:00Z',
    updated_at: '2024-01-25T14:12:00Z',
  },
  {
    id: 'item-003',
    offer_draft_id: 'offer-001',
    position_number: '01.01.02.0010',
    sort_order: 3,
    title: 'GK-Brandwand W115 F90',
    description: 'Brandschutzwand F90-A nach DIN 4102',
    long_text: null,
    quantity: 85.0,
    unit: 'm2',
    unit_price: 85.00,
    total_price: 7225.00,
    takeoff_result_id: null,
    price_library_id: 'price-003',
    extracted_data_id: 'ext-003',
    item_markup_percent: null,
    item_discount_percent: null,
    is_optional: false,
    is_alternative: false,
    parent_item_id: null,
    internal_notes: 'Klärung Brandschutzanforderung erforderlich!',
    created_at: '2024-01-25T14:14:00Z',
    updated_at: '2024-01-25T14:14:00Z',
  },
  {
    id: 'item-004',
    offer_draft_id: 'offer-001',
    position_number: '01.02.01.0010',
    sort_order: 4,
    title: 'GK-Abhangdecke D112',
    description: 'Geschlossene Deckenfläche, Abhängehöhe 30-50cm',
    long_text: null,
    quantity: 620.0,
    unit: 'm2',
    unit_price: 38.00,
    total_price: 23560.00,
    takeoff_result_id: null,
    price_library_id: 'price-004',
    extracted_data_id: 'ext-004',
    item_markup_percent: null,
    item_discount_percent: null,
    is_optional: false,
    is_alternative: false,
    parent_item_id: null,
    internal_notes: null,
    created_at: '2024-01-25T14:16:00Z',
    updated_at: '2024-01-25T14:16:00Z',
  },
  {
    id: 'item-005',
    offer_draft_id: 'offer-001',
    position_number: '01.02.02.0010',
    sort_order: 5,
    title: 'GK-Abhangdecke D113 Nassraum',
    description: 'Nassraumdecke mit imprägnierten Platten',
    long_text: null,
    quantity: 45.0,
    unit: 'm2',
    unit_price: 48.00,
    total_price: 2160.00,
    takeoff_result_id: null,
    price_library_id: 'price-005',
    extracted_data_id: 'ext-005',
    item_markup_percent: null,
    item_discount_percent: null,
    is_optional: false,
    is_alternative: false,
    parent_item_id: null,
    internal_notes: null,
    created_at: '2024-01-25T14:18:00Z',
    updated_at: '2024-01-25T14:18:00Z',
  },
];

// =============================================================================
// RUNTIME DATA STORE (persists during session)
// =============================================================================

// These arrays store data created during the session
export const RUNTIME_PROJECTS: Project[] = [];
export const RUNTIME_DOCUMENTS: Document[] = [];

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

export function getProjectById(id: string): Project | undefined {
  // Check runtime projects first, then demo projects
  return RUNTIME_PROJECTS.find(p => p.id === id) || DEMO_PROJECTS.find(p => p.id === id);
}

export function getAllProjects(): Project[] {
  return [...RUNTIME_PROJECTS, ...DEMO_PROJECTS];
}

export function addProject(project: Partial<Project>): Project {
  const newProject: Project = {
    id: `project-${Date.now()}`,
    company_id: project.company_id || DEMO_COMPANY.id,
    title: project.title || 'Neues Projekt',
    project_number: project.project_number || null,
    description: project.description || null,
    client_name: project.client_name || '',
    client_contact: project.client_contact || null,
    client_email: project.client_email || null,
    client_phone: project.client_phone || null,
    client_address: project.client_address || null,
    site_street: project.site_street || null,
    site_zip_code: project.site_zip_code || null,
    site_city: project.site_city || null,
    site_country: project.site_country || 'Deutschland',
    submission_deadline: project.submission_deadline || null,
    start_date: project.start_date || null,
    end_date: project.end_date || null,
    status: project.status || 'draft',
    total_net: project.total_net || 0,
    total_gross: project.total_gross || 0,
    tags: project.tags || [],
    notes: project.notes || null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: project.created_by || DEMO_USER.id,
  };
  RUNTIME_PROJECTS.unshift(newProject); // Add to beginning
  return newProject;
}

export function addDocument(doc: Partial<Document>): Document {
  const newDoc: Document = {
    id: `doc-${Date.now()}`,
    project_id: doc.project_id || '',
    name: doc.name || 'Dokument',
    original_filename: doc.original_filename || 'document.pdf',
    storage_path: doc.storage_path || `/uploads/${Date.now()}.pdf`,
    file_size: doc.file_size || 0,
    mime_type: doc.mime_type || 'application/pdf',
    document_type: doc.document_type || 'leistungsverzeichnis',
    status: doc.status || 'uploaded',
    page_count: doc.page_count || null,
    processing_started_at: null,
    processing_completed_at: null,
    processing_error: null,
    scale: null,
    drawing_number: null,
    revision: null,
    extraction_summary: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    uploaded_by: doc.uploaded_by || DEMO_USER.id,
  };
  RUNTIME_DOCUMENTS.push(newDoc);
  return newDoc;
}

export function getDocumentsByProjectId(projectId: string): Document[] {
  const runtimeDocs = RUNTIME_DOCUMENTS.filter(d => d.project_id === projectId);
  const demoDocs = DEMO_DOCUMENTS.filter(d => d.project_id === projectId);
  return [...runtimeDocs, ...demoDocs];
}

export function getExtractedDataByProjectId(projectId: string): ExtractedData[] {
  return DEMO_EXTRACTED_DATA.filter(e => e.project_id === projectId);
}

export function getTakeoffResultsByProjectId(projectId: string): TakeoffResult[] {
  return DEMO_TAKEOFF_RESULTS.filter(t => t.project_id === projectId);
}

export function getRiskFlagsByProjectId(projectId: string): RiskFlag[] {
  return DEMO_RISK_FLAGS.filter(r => r.project_id === projectId);
}

export function getOfferDraftsByProjectId(projectId: string): OfferDraft[] {
  return DEMO_OFFER_DRAFTS.filter(o => o.project_id === projectId);
}

export function getOfferLineItemsByOfferId(offerId: string): OfferLineItem[] {
  return DEMO_OFFER_LINE_ITEMS.filter(i => i.offer_draft_id === offerId);
}

export function getPriceLibraryByCompanyId(companyId: string): PriceLibraryItem[] {
  return DEMO_PRICE_LIBRARY.filter(p => p.company_id === companyId);
}

// Check if running in demo mode
export function isDemoMode(): boolean {
  return !process.env.NEXT_PUBLIC_SUPABASE_URL ||
         !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
         process.env.NEXT_PUBLIC_DEMO_MODE === 'true';
}
