
import React from 'react';
import { Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  de: {
    appName: 'AngebotsAgent',
    heroMicro: 'Explizit für Nachunternehmer im Bau',
    heroTitle: 'Angebote schnell erstellen. Aufträge sicher gewinnen.',
    heroSubtitle: 'Wir entwickeln Ihren eigenen AngebotsAgent als Dashboard-Funktion, der Mengen aus Plänen zieht, Nachtragspotentiale erkennt und VOB-konforme Angebote in Ihrem Branding erstellt. Keine monatlichen hohen Lizensgebühren, das Ding gehört Ihnen!',
    ctaDemo: 'System anfragen',
    ctaLogin: 'Login',
    footer: '© 2024 AngebotsAgent. Ihr Eigentum. Ihre Marge. Ihre Zukunft.',
    projects: 'Projekte',
    newProject: 'Neues Projekt',
    analyze: 'Dokumente analysieren',
    risks: 'Nachtragspotenziale',
    quantities: 'Massenermittlung',
    offer: 'Angebot erstellen',
    settings: 'Einstellungen',
    priceLibrary: 'Preisbibliothek',
    analytics: 'Erfolgs-Dashboard',
    support: 'Technischer Support',
    save: 'Speichern',
    examples: 'Beispiele',
    ownershipLabel: 'Eigentums-Prinzip',
    coreFeatures: 'Kern-Funktionen',
    inbox: 'Posteingang',
    tenders: 'Ausschreibungen',
    calculations: 'Kalkulationen',
    billing: 'Abrechnung',
    materials: 'Materialien',
    knowledge: 'Wissen',
    audit: 'Audit-Log'
  },
  en: {
    appName: 'AngebotsAgent',
    heroMicro: 'Explicitly for construction subcontractors',
    heroTitle: 'Create offers fast. Win contracts reliably.',
    heroSubtitle: 'We develop your custom AngebotsAgent as a dashboard-function to extract quantities, identify risks, and generate VOB-compliant offers in your branding. No high monthly license fees, the thing belongs to you!',
    ctaDemo: 'Request System',
    ctaLogin: 'Login',
    footer: '© 2024 AngebotsAgent. Your Ownership. Your Margin. Your Future.',
    projects: 'Projects',
    newProject: 'New Project',
    analyze: 'Analyze Documents',
    risks: 'Change Potential',
    quantities: 'Quantity Takeoff',
    offer: 'Generate Offer',
    settings: 'Settings',
    priceLibrary: 'Price Library',
    analytics: 'Performance Analytics',
    support: 'Technical Support',
    save: 'Save',
    examples: 'Examples',
    ownershipLabel: 'Ownership Principle',
    coreFeatures: 'Core Features',
    inbox: 'Inbox',
    tenders: 'Tenders',
    calculations: 'Calculations',
    billing: 'Billing',
    materials: 'Materials',
    knowledge: 'Knowledge',
    audit: 'Audit Log'
  }
};
